[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xpcscope"
version = "1.1.0"
description = "Yet another XPC sniffer"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "frida>=17.2.15",
]

[project.scripts]
xpcscope = "xpcscope.main:cli"

[tool.setuptools.packages.find]
exclude = ["agent*", "tests*", "examples*"]

[tool.setuptools.package-data]
xpcscope = ["lua/*.lua", "lua/**/*.lua", "agent/*.js"]
